force-app/main/default/objects/Exchange__c/Exchange__c.object-meta.xml
<CustomObject>
    <label>Exchange</label>
    <nameField>
        <displayFormat>EX-{000}</displayFormat>
        <label>Exchange Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exchanges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/workshopIntegration/objects/Exchange__c/fields/Currency_Name__c.field-meta.xml
<CustomField>
    <fullName>Currency_Name__c</fullName>
    <label>Currency Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AED</fullName>
            </value>
            <value>
                <fullName>AFN</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>AMD</fullName>
            </value>
            <value>
                <fullName>ANG</fullName>
            </value>
            <value>
                <fullName>AOA</fullName>
            </value>
            <value>
                <fullName>ARS</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>AWG</fullName>
            </value>
            <value>
                <fullName>AZN</fullName>
            </value>
            <value>
                <fullName>BAM</fullName>
            </value>
            <value>
                <fullName>BBD</fullName>
            </value>
            <value>
                <fullName>BDT</fullName>
            </value>
            <value>
                <fullName>BGN</fullName>
            </value>
            <value>
                <fullName>BHD</fullName>
            </value>
            <value>
                <fullName>BIF</fullName>
            </value>
            <value>
                <fullName>BMD</fullName>
            </value>
            <value>
                <fullName>BND</fullName>
            </value>
            <value>
                <fullName>BOB</fullName>
            </value>
            <value>
                <fullName>BRL</fullName>
            </value>
            <value>
                <fullName>BSD</fullName>
            </value>
            <value>
                <fullName>BTC</fullName>
            </value>
            <value>
                <fullName>BTN</fullName>
            </value>
            <value>
                <fullName>BWP</fullName>
            </value>
            <value>
                <fullName>BYN</fullName>
            </value>
            <value>
                <fullName>BYR</fullName>
            </value>
            <value>
                <fullName>BZD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>CDF</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/workshopIntegration/classes/ExchangeRestCallout.cls
public with sharing class ExchangeRestCallout {
    //.url("https://api.apilayer.com/exchangerates_data/latest?symbols=symbols&base=base")
    //.addHeader("apikey", "EiqhbU8lledxpGj5PYknG7wJZcWikej4")
    @invocableMethod (label= 'Exchange Callout'
                       description = 'Bu method kur değerlerini getirmek için kullnılmaktadır.' 
                       category = 'Exchange Callout')
    public static void getExchangeRate(List<id> exchangeIDs){

        List<Exchange__c> listExchange = [SELECT Currency_Name__c, Exchange_Rate__c FROM Exchange__c WHERE ID IN : exchangeIDs];
        List<Exchange__c> listExchangeUpdate = new List<Exchange__c>();

        for (Exchange__c ex : listExchange) {       
            string currencyName = ex.Currency_Name__c;
            HttpRequest request = new HttpRequest();
            request.setEndpoint('https://api.apilayer.com/exchangerates_data/latest?symbols='+ currencyName +'&base=USD');
            request.setMethod('GET');
            request.setHeader('apikey', 'EiqhbU8lledxpGj5PYknG7wJZcWikej4');
            request.setTimeout(20000);
            
            Http http = new Http();
            HTTPResponse response = http.send(request);
            
            if (response.getStatusCode() == 200) {
                String responseBody = response.getBody();
                System.debug('responseBody: ' +responseBody);
                // Handle response
                // JSON verilerini ExchangeRate sınıfına dönüştürme
                EchangeWrapper.Rates exchangeRate = (EchangeWrapper.Rates) JSON.deserialize(responseBody, EchangeWrapper.Rates.class);
                // TRY kuru
                Decimal rate = exchangeRate.rates.get(currencyName);
                System.debug('kur: ' + rate);
                ex.Exchange_Rate__c= rate;
                listExchangeUpdate.add(ex);
                try {
                    update listExchangeUpdate;
                } catch (Exception exp) {
                    System.debug(exp);
                }
            } else {
                // Handle error
            }
    }
        
    }
}